### ISSUE TITLE
Mistake in Solution to Exercise 2.15?

### ISSUE THREAD

**Issue by lutalli** [9beach/jech-set-theory-solutions#1]
In the proof of Exercise 2.15 we got the following sentence:
```tex
Let $T=\{g:g$ is a function such that $\text{dom}(g)$ is $E$-transitive in $P$ and $g(x)=G(x,g\upharpoonright x)$ for all $x\in\text{ dom}(g)\}$.
```
where `$g(x)=G(x,g\upharpoonright x)$` should read `$g(x)=G(x,g\upharpoonright\{y\in\mathrm{dom}(g):y\,E\,x\})$`, I believe.

![image](https://user-images.githubusercontent.com/47910890/132984268-00d779cd-13b3-4332-bd3a-cb150ce02d30.png)

**Comment by 9beach** [comment]
My apologies for the late reply. You're right. I was confused well-founded relation with the ordinals (for example, "↾3 == ↾{ 0, 1, 2 } == ↾ { less than 3 }). In this case, not "↾ x" but "↾ {y∈dom(g):y E x}" is correct. Thank you!
